### ISSUE TITLE
Connections not being released

### ISSUE THREAD

**Issue by nrempel** [blockai/advisory-lock#1]
First off - thanks for the great library!

I'm currently troubleshooting an issue with connections not being released after using `withLock()`. I'll update the issue as I go but if you have any pointers that would be greatly appreciated. Thanks!

**Comment by nrempel** [comment]
It seems that every lock that is acquired holds a connection indefinitely.

If I perform 10 atomic operations with an advisory lock, there are 10 active connections in the database. The connections are never released so eventually, I hit my limit.

**Comment by nrempel** [comment]
It looks like `pg.Client()` should call `.end()` and `pg.connect()` manages its own connection pool. - https://github.com/brianc/node-postgres#client-instance

I _think_ I've fixed my issue by adding `client.end()` for both response cases here: https://github.com/blockai/advisory-lock/blob/master/src/index.js#L107.

I'll try to see if I can write a failing test later today

**Comment by olalonde** [comment]
Yes, I think there's one connection created per `advisoryLock(connectionString)` but it should be disconnected when there are no lock held. Could you provide some sample code that's causing an issue for you? I didn't use node-postgres connection pool because I had to do connection specific stuff if I recall correctly.

edit: Oh yeah, if one connection acquires a lock, subsequent attempts to acquire the lock from the same connection will succeed but it will fail if done from a different connection.

**Comment by nrempel** [comment]
Hi @olalonde thanks for getting back so quick!

I created a test for an example of the problem I'm having. https://github.com/blockai/advisory-lock/pull/2

The test is just an example using print statements right now. I'm having a hard time making it consistently fail because of the odd case. But if you run that branch, it should give you an example of the problem I'm having.

Edit: I updated the pull request to properly include a failing test and a change to resolve the issue.
